import { ArrowUpRight, CheckCircle2, Flame, Globe2, Heart, Recycle, ShieldCheck, Sparkles, Target, Trophy, Users } from "lucide-react";
import GameShell from "@/components/GameShell";
import ActionForm from "@/components/ActionForm";
import RewardCard from "@/components/RewardCard";
import { demoActions, demoRewards, demoUser, leaderboard } from "@/lib/demo";

export default function Home(){
 const level=Math.floor(demoUser.xp/500)+1; const progress=(demoUser.xp%500)/5;
 return <GameShell><main id="top">
  <section className="container hero"><div><div className="eyebrow">CLIMATE-TECH • SOCIAL IMPACT • LIVE COMPETITION</div><h1>ECO-<span>WARRIOR</span><br/>ZERO WASTE<br/>CLIMATE WAR</h1><p>Your real-world actions become your power. Log measurable climate actions, earn Eco-Tokens, get community verified, and race for limited sponsor rewards.</p><div className="actions"><a className="btn primary" href="#action">START ECO WAR <ArrowUpRight size={17} style={{verticalAlign:'middle'}}/></a><a className="btn" href="#war">VIEW LIVE WAR</a></div><div className="meta"><Globe2 size={15} className="cyan"/> GLOBAL IMPACT NETWORK <span>•</span> <Users size={15}/> 12,482 ECO-WARRIORS ONLINE</div></div><div className="orbit"><div className="earth"/><div className="orbit-label"><span className="muted">GLOBAL TARGET</span><strong>84%</strong><span className="muted">842,120 kg CO₂e</span></div></div></section>
  <section id="dashboard" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">COMMAND CENTER</div><h2>Your Eco-Warrior Profile</h2></div><div className="profile"><div className="avatar">P</div><div><strong>{demoUser.username}</strong><div className="rank">🌳 CLIMATE GUARDIAN • LEVEL {level}</div></div></div></div><div className="grid stats"><div className="card stat"><div className="label">CO₂ Reduced</div><div className="value green">{demoUser.co2Reduced} kg</div><div className="muted">estimated verified impact</div></div><div className="card stat"><div className="label">Waste Diverted</div><div className="value cyan">{demoUser.wasteDiverted} kg</div><div className="muted">kept out of landfill</div></div><div className="card stat"><div className="label">Verified Actions</div><div className="value">{demoUser.verifiedActions}</div><div className="muted">community approved</div></div><div className="card stat"><div className="label">Reputation</div><div className="value gold">{demoUser.reputation}%</div><div className="muted">trust score</div></div></div><div className="grid dashboard" style={{marginTop:16}}><div className="card"><div className="section-head"><div><strong>LEVEL {level} PROGRESS</strong><div className="muted">{demoUser.xp} XP • next level at {(level)*500} XP</div></div><span className="green">{Math.round(progress)}%</span></div><div className="progress"><i style={{width:`${Math.max(4,progress)}%`}}/></div><div className="impact-row"><span>Eco-Tokens</span><strong className="gold">₳ {demoUser.ecoTokens.toLocaleString()}</strong></div><div className="impact-row"><span>Current Rank</span><strong>#12 GLOBAL</strong></div></div><div className="card"><div className="eyebrow">NEXT MILESTONE</div><h3>CARBON WARRIOR</h3><p className="muted">Reach 1,000 kg CO₂e verified impact to unlock the badge.</p><div className="progress"><i style={{width:'72%'}}/></div><div className="meta" style={{marginTop:12}}><Target size={15}/> 720 / 1,000 kg</div></div></div></div></section>

  <section id="war" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">LIVE GLOBAL EVENT</div><h2>⚔ ZERO WASTE WAR</h2></div><span className="pill verified">● WAR ACTIVE</span></div><div className="card"><div className="grid stats"><div><div className="label">TIME REMAINING</div><div className="value mono">17:42:31</div></div><div><div className="label">WARRIORS</div><div className="value">12,482</div></div><div><div className="label">CO₂ REDUCED</div><div className="value green">842,120 kg</div></div><div><div className="label">WASTE DIVERTED</div><div className="value cyan">291,210 kg</div></div></div><div style={{marginTop:25}}><div className="section-head"><strong>GLOBAL TARGET • 1,000,000 KG WASTE DIVERSION</strong><strong className="green">84%</strong></div><div className="progress" style={{height:13}}><i style={{width:'84%'}}/></div></div></div></div></section>

  <section id="action" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">REAL-WORLD IMPACT</div><h2>Log Your Eco Action</h2></div><span className="pill">SERVER-SIDE IMPACT ENGINE</span></div><ActionForm/></div></section>

  <section id="feed" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">COMMUNITY VALIDATION</div><h2>Eco Feed</h2></div><span className="muted">Like • Dislike • Report</span></div><div className="grid feed">{demoActions.map(a=><article className="card action-card" key={a.id}><div className="meta"><div className="avatar" style={{width:34,height:34,borderRadius:11}}>{a.username[0]}</div><strong style={{color:'#dceee4'}}>{a.username}</strong><span>•</span><span>{a.time}</span></div><div style={{marginTop:14}}><span className="pill">{a.category}</span> <span className={`pill ${a.status==='VERIFIED'?'verified':'pending'}`}>{a.status==='VERIFIED'?'✓ VERIFIED':'PENDING VALIDATION'}</span></div><h3>{a.title}</h3><p className="muted">{a.description}</p><div className="impact-row"><span>↓ CO₂e</span><strong className="green">{a.co2Reduced} kg</strong></div><div className="impact-row"><span>↓ Waste</span><strong className="cyan">{a.wasteDiverted} kg</strong></div><div className="vote-row"><button className="vote"><Heart size={14}/> {a.likes}</button><button className="vote">👎 {a.dislikes}</button><button className="vote">🚩 {a.reports}</button></div></article>)}</div></div></section>

  <section id="vault" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">LIMITED SUPPLY • FIRST COME, FIRST SERVED</div><h2>War Rewards Vault</h2></div><div className="pill invalid"><Flame size={13}/> CRITICAL STOCK ACTIVE</div></div><div className="grid vault">{demoRewards.map(r=><RewardCard key={r.id} reward={r}/>)}</div></div></section>

  <section id="leaderboard" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">GLOBAL RANKING</div><h2>Eco-Warrior Leaderboard</h2></div><span className="pill">GLOBAL • WEEKLY</span></div><div className="card"><table className="table"><thead><tr><th>#</th><th>Warrior</th><th>CO₂ Impact</th><th>Waste</th><th>Verified</th></tr></thead><tbody>{leaderboard.map((x,i)=><tr key={x[0] as string}><td className="ranknum">{i+1}</td><td><strong>{x[0]}</strong>{i===0&&<span className="pill verified" style={{marginLeft:8}}>YOU</span>}</td><td className="green">{x[1]} kg</td><td>{x[2]} kg</td><td>{x[3]} actions</td></tr>)}</tbody></table></div></div></section>

  <section id="sponsors" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">IMPACT PARTNERS</div><h2>Sponsor Eco-War</h2></div><a className="btn" href="#footer">BECOME A SPONSOR <ArrowUpRight size={15} style={{verticalAlign:'middle'}}/></a></div><div className="grid stats"><div className="card"><ShieldCheck className="green"/><h3>Green Mobility</h3><p className="muted">Funding sustainable transport rewards and measuring verified mobility impact.</p></div><div className="card"><Recycle className="cyan"/><h3>Bali Circular</h3><p className="muted">Supporting composting, reuse and waste diversion campaigns.</p></div><div className="card"><Sparkles className="gold"/><h3>Ocean Future</h3><p className="muted">Rewarding plastic reduction and community clean-up actions.</p></div><div className="card"><Trophy className="green"/><h3>Impact Analytics</h3><p className="muted">Sponsors receive campaign impact, views, likes, feedback and engagement analytics.</p></div></div></div></section>
 </main><footer id="footer" className="footer"><div className="container"><strong>ECO-WARRIOR: ZERO WASTE CLIMATE WAR</strong><p>Climate action as a competitive social game. Estimated impacts are based on configurable emission factors and should be interpreted as estimates.</p><div className="meta">Demo Mode • Vercel Ready • putuprofile.me</div></div></footer></GameShell>
}
